services:
  LoadBalancer:
    image: nginx:latest
    container_name: LoadBalancer
    hostname: LoadBalancer
    ports:
      - "20000:8000"
    networks:
      FrontendNet:
        ipv4_address: 172.20.0.10
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro

  WebServer1:
    build:
      context: ./docker/webserver2
      dockerfile: Dockerfile
    image: webserver1
    container_name: WebServer1
    hostname: WebServer1
    networks:
      FrontendNet: { ipv4_address: 172.20.0.11 }
      BackendNet : { ipv4_address: 172.21.0.11 }

  WebServer2:
    build:
      context: ./docker/webserver2
      dockerfile: Dockerfile
    image: webserver2
    container_name: WebServer2
    hostname: WebServer2
    networks:
      FrontendNet: { ipv4_address: 172.20.0.12 }
      BackendNet : { ipv4_address: 172.21.0.12 }

  WebServer3:
    build:
      context: ./docker/webserver2
      dockerfile: Dockerfile
    image: webserver3
    container_name: WebServer3
    hostname: WebServer3
    networks:
      FrontendNet: { ipv4_address: 172.20.0.13 }
      BackendNet : { ipv4_address: 172.21.0.13 }

  WebServer4:
    build:
      context: ./docker/webserver2
      dockerfile: Dockerfile
    image: webserver4
    container_name: WebServer4
    hostname: WebServer4
    networks:
      FrontendNet: { ipv4_address: 172.20.0.14 }
      BackendNet : { ipv4_address: 172.21.0.14 }

  WebServer5:
    build:
      context: ./docker/webserver2
      dockerfile: Dockerfile
    image: webserver5
    container_name: WebServer5
    hostname: WebServer5
    networks:
      FrontendNet: { ipv4_address: 172.20.0.15 }
      BackendNet : { ipv4_address: 172.21.0.15 }

  Database:
    image: postgres:14-alpine
    container_name: Database
    hostname: Database
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: secure1234
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      BackendNet   : { ipv4_address: 172.21.0.10 }
      ManagementNet: { ipv4_address: 172.22.0.10 }

  DataBaseManager:
    image: dpage/pgadmin4:latest
    container_name: DataBaseManager
    hostname: DataBaseManager
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secretsecret
      PGADMIN_LISTEN_PORT: 8000
    ports:
      - "20001:8000"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      ManagementNet: { ipv4_address: 172.22.0.11 }

networks:
  FrontendNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  BackendNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
  ManagementNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  db-data:
  pgadmin-data:
